
CREATE DATABASE PIM1 --AQUI VOCÊ COLOCA O NOME DO BANCO QUE SERÁ CRIADO

GO --PROXIMO COMANDO A SER EXECULTADO  

USE PIM1 --SELECIONAR O BANCO QUE SERÁ USADO 

GO


--TABELA DE ENDEREÇO
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Endereco]'))
CREATE TABLE TB_Endereco
(
ENDE_ID INT NOT NULL IDENTITY (1,1),
ENDE_Numero INT,
ENDE_Comprimento VARCHAR (20),
ENDE_Bairro VARCHAR (60),
ENDE_Municipio VARCHAR (60),
ENDE_Estado VARCHAR(60),
ENDE_CEP INT NOT NULL,
ENDE_Cidade VARCHAR(40),
ID_Pessoa INT NOT NULL,
PRIMARY KEY (ENDE_ID),
CONSTRAINT FK_TB_Pessoa FOREIGN KEY (ID_Pessoa) REFERENCES TB_Pessoa (ID_Pessoa),
);

--TABELA DE Pessoa
GO
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Pessoa]'))
CREATE TABLE TB_Pessoa
(
ID_Pessoa INT  not null IDENTITY (1,1),
ID_CPF INT not null UNIQUE,
RG VARCHAR (50) UNIQUE ,
Nome VARCHAR (50),
DataNasc DATE,
Sexo VARCHAR(1),
PRIMARY KEY (ID_Pessoa),

);

--TABELA DE EMPRESAS
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Empresa]'))
CREATE TABLE TB_Empresa
(
EMP_ID INT  IDENTITY (1,1) NOT NULL,
EMP_CNPJ INT NOT NULL UNIQUE,
EMP_RazaoSocial VARCHAR (50) UNIQUE,
ID_ENDE_EMP INT NOT NULL,
PRIMARY KEY (EMP_ID),
CONSTRAINT FK_ENDE_EMP FOREIGN KEY (ID_ENDE_EMP) REFERENCES TB_Endereco (ENDE_ID),
);


--TABELA DE MOTORISTAS
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Motorista]'))
CREATE TABLE TB_Motorista
(
Mot_ID INT IDENTITY not null,
CNH INT NOT NULL,
--Mot_IDEMP INT NOT NULL,
ID_PessoaM INT NOT NULL,
ID_EmpresaM INT NOT NULL,
CONSTRAINT FK_EMPRESAM FOREIGN KEY (ID_EmpresaM) REFERENCES TB_Empresa (EMP_ID),
CONSTRAINT FK_PESSOAM FOREIGN KEY (ID_PessoaM) REFERENCES TB_Pessoa (ID_Pessoa),
PRIMARY KEY (Mot_ID),
);

--TABELA DE PERFILS

IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Perfil]'))
CREATE TABLE TB_Perfil
(
Per_ID INT IDENTITY (1,1) not null,
Cargo VARCHAR (50),
PRIMARY KEY (Per_ID),
);


--TABELA DE Funcioanrio
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Funcionario]'))
CREATE TABLE TB_Funcionario
(
Fun_ID INT IDENTITY not null,
ID_Perfil INT NOT NULL,
ID_Pessoa INT NOT NULL,
Salario DECIMAL, 
CONSTRAINT FK_PerfilF FOREIGN KEY (ID_Perfil) REFERENCES TB_Perfil (Per_ID),
CONSTRAINT FK_PESSOAF FOREIGN KEY (ID_Pessoa) REFERENCES TB_Pessoa (ID_Pessoa),
PRIMARY KEY (Fun_ID),
);





--TABELA DE EMPRESAS
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Empresa]'))
CREATE TABLE TB_Empresa
(
EMP_ID INT  IDENTITY (1,1) NOT NULL,
EMP_CNPJ INT NOT NULL UNIQUE,
EMP_RazaoSocial VARCHAR (50) UNIQUE,
PRIMARY KEY (EMP_ID),
);

--TABELA DE VEICULOS
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Veiculo]'))
CREATE TABLE TB_Veiculo
(
Vei_IDVeiculo INT IDENTITY (1,1) not null,
Vei_Placa INT  NOT NULL UNIQUE,
Vei_Marca  VARCHAR (50),
Vei_Modelo VARCHAR (50),
Vei_Renavam INT,
Vei_Cor VARCHAR (20),
Mar_Marca VARCHAR (20),
ID_EmpresaV INT NOT NULL,
CONSTRAINT FK_EMPRESAV FOREIGN KEY (ID_EmpresaV) REFERENCES TB_Empresa (EMP_ID),
PRIMARY KEY (Vei_IDVeiculo),
);




--TABELA DE TELEFONES
IF NOT EXISTS (SELECT ID FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.[TB_Telefone]'))
CREATE TABLE TB_Telefone
(
Tel_id INT NOT NULL IDENTITY (1,1),
Tel_DDI INT NOT NULL,
Tel_DDD INT NOT NULL,
Tel_Telefone INT NOT NULL UNIQUE,
ID_PessoaTel int not null,
CONSTRAINT FK_PessoaTel FOREIGN KEY (ID_PessoaTel) REFERENCES TB_Pessoa (ID_Pessoa),
PRIMARY KEY (Tel_id)
);